//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV_Blazor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string ab_DownloadCV {
            get {
                return ResourceManager.GetString("ab_DownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my projects.
        /// </summary>
        public static string ab_Projects {
            get {
                return ResourceManager.GetString("ab_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, my name is Maximo.
        /// </summary>
        public static string ab_Title {
            get {
                return ResourceManager.GetString("ab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string cs_contactInformation {
            get {
                return ResourceManager.GetString("cs_contactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact me:.
        /// </summary>
        public static string cs_contactMe {
            get {
                return ResourceManager.GetString("cs_contactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string nav_AboutMe {
            get {
                return ResourceManager.GetString("nav_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string nav_Contact {
            get {
                return ResourceManager.GetString("nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string nav_DarkMode {
            get {
                return ResourceManager.GetString("nav_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string nav_Home {
            get {
                return ResourceManager.GetString("nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string nav_Projects {
            get {
                return ResourceManager.GetString("nav_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string nav_Resume {
            get {
                return ResourceManager.GetString("nav_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string nav_Skills {
            get {
                return ResourceManager.GetString("nav_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 2D psychological horror game developed in 3 days for a Game Jam..
        /// </summary>
        public static string ps_bitter_surprises_desc {
            get {
                return ResourceManager.GetString("ps_bitter_surprises_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter Surprises.
        /// </summary>
        public static string ps_bitter_surprises_title {
            get {
                return ResourceManager.GetString("ps_bitter_surprises_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An academic simulator developed for the university, focused on simulating an earthquake and localized in several languages for a global audience..
        /// </summary>
        public static string ps_earthquake_simulator_desc {
            get {
                return ResourceManager.GetString("ps_earthquake_simulator_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthquake Simulator (University Project).
        /// </summary>
        public static string ps_earthquake_simulator_title {
            get {
                return ResourceManager.GetString("ps_earthquake_simulator_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician in Video Game Development.
        /// </summary>
        public static string ps_edu_unimendoza_title {
            get {
                return ResourceManager.GetString("ps_edu_unimendoza_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and programmed gameplay mechanics and combat systems for a hack and slash style action role-playing game..
        /// </summary>
        public static string ps_exp_abi_rached_ach_1 {
            get {
                return ResourceManager.GetString("ps_exp_abi_rached_ach_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible for implementing animation systems and enemy logic in Unity..
        /// </summary>
        public static string ps_exp_abi_rached_ach_2 {
            get {
                return ResourceManager.GetString("ps_exp_abi_rached_ach_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Programmer.
        /// </summary>
        public static string ps_exp_abi_rached_title {
            get {
                return ResourceManager.GetString("ps_exp_abi_rached_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I performed the animation cleanup and optimization process in Unreal Engine to improve the movement fidelity and project efficiency..
        /// </summary>
        public static string ps_exp_xowen_ach_1 {
            get {
                return ResourceManager.GetString("ps_exp_xowen_ach_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I collaborated in integrating animations into the game engine..
        /// </summary>
        public static string ps_exp_xowen_ach_2 {
            get {
                return ResourceManager.GetString("ps_exp_xowen_ach_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Clean Up (Intern).
        /// </summary>
        public static string ps_exp_xowen_title {
            get {
                return ResourceManager.GetString("ps_exp_xowen_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interactive resume hosted on www.3d.maximobrunetti.com.ar, developed with Needle Engine and Three.js to create an immersive experience..
        /// </summary>
        public static string ps_interactive_website_desc {
            get {
                return ResourceManager.GetString("ps_interactive_website_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Personal Website.
        /// </summary>
        public static string ps_interactive_website_title {
            get {
                return ResourceManager.GetString("ps_interactive_website_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects.
        /// </summary>
        public static string ps_myProjects {
            get {
                return ResourceManager.GetString("ps_myProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See project.
        /// </summary>
        public static string ps_seeProject {
            get {
                return ResourceManager.GetString("ps_seeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a software developer with experience in C# and Unity..
        /// </summary>
        public static string ps_summary_1 {
            get {
                return ResourceManager.GetString("ps_summary_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am passionate about creating innovative mechanics..
        /// </summary>
        public static string ps_summary_2 {
            get {
                return ResourceManager.GetString("ps_summary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am looking to contribute to challenging projects..
        /// </summary>
        public static string ps_summary_3 {
            get {
                return ResourceManager.GetString("ps_summary_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game developed for the Global Game Jam 2024..
        /// </summary>
        public static string ps_the_last_laugh_desc {
            get {
                return ResourceManager.GetString("ps_the_last_laugh_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Laugh.
        /// </summary>
        public static string ps_the_last_laugh_title {
            get {
                return ResourceManager.GetString("ps_the_last_laugh_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mobile game developed in Unity, where the character&apos;s control is based on the device&apos;s gyroscope, simulating the balance of a tightrope walker..
        /// </summary>
        public static string ps_tightrope_walker_desc {
            get {
                return ResourceManager.GetString("ps_tightrope_walker_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tightrope Walker: Gyroscope.
        /// </summary>
        public static string ps_tightrope_walker_title {
            get {
                return ResourceManager.GetString("ps_tightrope_walker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string rs_education {
            get {
                return ResourceManager.GetString("rs_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Experience.
        /// </summary>
        public static string rs_xp {
            get {
                return ResourceManager.GetString("rs_xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have modeled and textured in 3D using Blender, focusing on optimizing models with high polygon density and multiple materials. I have experience creating animations from scratch and integrating them directly into my video game projects..
        /// </summary>
        public static string ss_Blender_Description {
            get {
                return ResourceManager.GetString("ss_Blender_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid experience in C# with a primary focus on video game development in the Unity engine. I have extensive knowledge of design patterns (such as Singleton, Observer, and Factory) and best practices. Additionally, I have worked with the .NET environment, including projects with ASP.NET and Blazor, which allows me to create web applications like this one..
        /// </summary>
        public static string ss_C__Description {
            get {
                return ResourceManager.GetString("ss_C#_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have experience using Git for both individual and team projects, demonstrating a solid understanding of version control workflows. I strategically use commits and tags as checkpoints to manage the code history. I have worked with platforms like GitHub and GitLab for collaboration and project deployment..
        /// </summary>
        public static string ss_Git_Description {
            get {
                return ResourceManager.GetString("ss_Git_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have knowledge of JavaScript and TypeScript, mainly applied in the development of interactive and web experiences. I have experience working with Needle Engine within Unity and with the Three.js library for 3D web projects. Additionally, I have basic experience in creating web pages..
        /// </summary>
        public static string ss_JS_TS_Description {
            get {
                return ResourceManager.GetString("ss_JS/TS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string ss_level1 {
            get {
                return ResourceManager.GetString("ss_level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        public static string ss_level2 {
            get {
                return ResourceManager.GetString("ss_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string ss_level3 {
            get {
                return ResourceManager.GetString("ss_level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ss_level4 {
            get {
                return ResourceManager.GetString("ss_level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string ss_level5 {
            get {
                return ResourceManager.GetString("ss_level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ss_levelLabel {
            get {
                return ResourceManager.GetString("ss_levelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic knowledge of Adobe Photoshop for image editing, resizing, and adaptation for different platforms. I have experience creating user interface (UI) elements, such as text, for implementation in projects..
        /// </summary>
        public static string ss_Photoshop_Description {
            get {
                return ResourceManager.GetString("ss_Photoshop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer with experience in the Unity engine, focused on 3D game development. I excel in programming game mechanics, creating simulators, and implementing user interface (UI) systems. I am also familiar with asset integration and modification, and I have knowledge of ShaderLab for creating visual effects and optimizing performance for mobile platforms..
        /// </summary>
        public static string ss_Unity_Description {
            get {
                return ResourceManager.GetString("ss_Unity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have worked with the Unreal engine, focusing on creating 3D environments, including landscapes and platforms. I have experience in asset integration, prototyping virtual reality (VR) projects, and working with animations..
        /// </summary>
        public static string ss_Unreal_Description {
            get {
                return ResourceManager.GetString("ss_Unreal_Description", resourceCulture);
            }
        }
    }
}
