//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Blazor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV_Blazor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string ab_DownloadCV {
            get {
                return ResourceManager.GetString("ab_DownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See my projects.
        /// </summary>
        public static string ab_Projects {
            get {
                return ResourceManager.GetString("ab_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, my name is Maximo.
        /// </summary>
        public static string ab_Title {
            get {
                return ResourceManager.GetString("ab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string cs_contactInformation {
            get {
                return ResourceManager.GetString("cs_contactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact me:.
        /// </summary>
        public static string cs_contactMe {
            get {
                return ResourceManager.GetString("cs_contactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string nav_AboutMe {
            get {
                return ResourceManager.GetString("nav_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string nav_Contact {
            get {
                return ResourceManager.GetString("nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string nav_DarkMode {
            get {
                return ResourceManager.GetString("nav_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string nav_Home {
            get {
                return ResourceManager.GetString("nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string nav_Projects {
            get {
                return ResourceManager.GetString("nav_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string nav_Resume {
            get {
                return ResourceManager.GetString("nav_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string nav_Skills {
            get {
                return ResourceManager.GetString("nav_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My projects.
        /// </summary>
        public static string ps_myProjects {
            get {
                return ResourceManager.GetString("ps_myProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See project.
        /// </summary>
        public static string ps_seeProject {
            get {
                return ResourceManager.GetString("ps_seeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string rs_education {
            get {
                return ResourceManager.GetString("rs_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Experience.
        /// </summary>
        public static string rs_xp {
            get {
                return ResourceManager.GetString("rs_xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string ss_level1 {
            get {
                return ResourceManager.GetString("ss_level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        public static string ss_level2 {
            get {
                return ResourceManager.GetString("ss_level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string ss_level3 {
            get {
                return ResourceManager.GetString("ss_level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ss_level4 {
            get {
                return ResourceManager.GetString("ss_level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        public static string ss_level5 {
            get {
                return ResourceManager.GetString("ss_level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ss_levelLabel {
            get {
                return ResourceManager.GetString("ss_levelLabel", resourceCulture);
            }
        }
    }
}
